//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Văn_Hòa_CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_DON_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHI_TIET_DON_HANG()
        {
            this.TOPPING_TRONG_DON_HANG = new HashSet<TOPPING_TRONG_DON_HANG>();
        }
    
        public int MA_CHI_TIET_DON_HANG { get; set; }
        public int MA_DON_HANG { get; set; }
        public int MA_SAN_PHAM { get; set; }
        public int MA_KICH_THUOC { get; set; }
        public int SO_LUONG { get; set; }
        public decimal THANH_TIEN { get; set; }
    
        public virtual DON_HANG DON_HANG { get; set; }
        public virtual KICH_THUOC KICH_THUOC { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOPPING_TRONG_DON_HANG> TOPPING_TRONG_DON_HANG { get; set; }
    }
}
