//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Văn_Hòa_CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI_VIEN
    {
        public int MA_QUAN_TRI { get; set; }
        public string TEN_DANG_NHAP { get; set; }
        public string MAT_KHAU { get; set; }
        public string VAI_TRO { get; set; }
    }
}
