//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Văn_Hòa_CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPPING_TRONG_DON_HANG
    {
        public int MA_TOPPING_DON_HANG { get; set; }
        public int MA_CHI_TIET_DON_HANG { get; set; }
        public int MA_TOPPING { get; set; }
        public int SO_LUONG_TOPPING { get; set; }
    
        public virtual CHI_TIET_DON_HANG CHI_TIET_DON_HANG { get; set; }
        public virtual TOPPING TOPPING { get; set; }
    }
}
